name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      REACT_APP_API_HOST: https://ntp.ksys.one
      REACT_APP_API_TODO: todo-service/todo
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use variables
        run: |
          echo "api_host variable : ${{ vars.REACT_APP_API_HOST }}"
          echo "api_todo variable : ${{ vars.REACT_APP_API_TODO }}"
          echo "process.env.REACT_APP_API_HOST : ${{ process.env.REACT_APP_API_HOST }}"
          echo "process.env.REACT_APP_API_TODO : ${{ process.env.REACT_APP_API_TODO }}"

      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build